# Generated by Django 2.1.3 on 2018-12-01 21:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AwesomeBank', '0002_auto_20181124_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=80)),
                ('recipient_account', models.CharField(max_length=26, validators=[django.core.validators.RegexValidator(message='Niewłaściwy numer konta - za mało cyfr', regex='[0-9]{26}')])),
                ('title', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_account',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
